src/objects/Attribute_Set__c.object
<CustomObject>
    <description>An Attribute Set contains related attribute definitions</description>
    <label>Attribute Set</label>
    <nameField>
        <label>Attribute Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Attribute_Set_Item__c.object
<CustomObject>
    <description>Definitions of attributes belonging to an attribute set.</description>
    <fields>
        <fullName>Attribute_Set__c</fullName>
        <label>Attribute Set</label>
        <referenceTo>Attribute_Set__c</referenceTo>
        <relationshipLabel>Attribute Set Items</relationshipLabel>
        <relationshipName>Attribute_Set_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute Set Item</label>
    <nameField>
        <label>Attribute Set Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Set Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AttributeSetController.cls
public class AttributeSetController {
    	@AuraEnabled
    	public static List<Attribute_Set__c> getAttributeSets() {
    		return [SELECT Name from Attribute_Set__c order by Name];
    	}
    	

    	public static List<Attribute_Set_Item__c> getAttributeSetItems(ID setId) {
    	  if (String.isBlank(setId)) {
    	    setId = 'a074100000BbKxfAAF';
    	  }
    	  return [Select Name from Attribute_Set_Item__c where Attribute_Set__c = :setId];
    	}
}